BulkyWeb/Areas/Admin/Controllers/OrderController.cs
using BulkyBook.DataAccess.Repository;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe;
using Stripe.Checkout;
using Stripe.Climate;
using System.Diagnostics;
using System.Security.Claims;

namespace BulkyBookWeb.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles =SD.Role_Adm)]
    public class OrderController : Controller
    {
        #region ctor
        private readonly IUnitOfWork unitOfWork;
        [BindProperty]
        public OrderVM OrderVM { get; set; }

        public OrderController(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        #endregion

        #region OrderDetails
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> Details(int orderId)
        {
           OrderVM = new()
            {
                OrderHeader = await unitOfWork.OrderHeader.GetFirstOrDefaultAsync(x => x.Id == orderId, false, x => x.ApplicationUser),
                OrderDetial = await unitOfWork.OrderDetail.GetAsync(x => x.OrderHeaderId == orderId, false, x => x.Product)

            };
           

            return View(OrderVM);
        }

        [HttpPost]
        [Authorize(Roles =SD.Role_Adm+","+SD.Role_Emp)]
        public async Task<IActionResult> UpdateOrderDetail()
        {
            var orderHeaderFroDb = await unitOfWork.OrderHeader.GetFirstOrDefaultAsync(x => x.Id == OrderVM.OrderHeader.Id);
            orderHeaderFroDb.Name = OrderVM.OrderHeader.Name;
            orderHeaderFroDb.PhoneNumber = OrderVM.OrderHeader.PhoneNumber;
            orderHeaderFroDb.City = OrderVM.OrderHeader.City;
            orderHeaderFroDb.StreetAddress = OrderVM.OrderHeader.StreetAddress;
            orderHeaderFroDb.PostalCode= OrderVM.OrderHeader.PostalCode;
            orderHeaderFroDb.State = OrderVM.OrderHeader.State;
            

            if (!string.IsNullOrEmpty(OrderVM.OrderHeader.Carrier))
            {
                orderHeaderFroDb.Carrier = OrderVM.OrderHeader.Carrier;


            }
            if (!string.IsNullOrEmpty(OrderVM.OrderHeader.TrackingNumber))
            {
                orderHeaderFroDb.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;

            }
            await unitOfWork.OrderHeader.CreateOrUpdateAsync(orderHeaderFroDb);

            await unitOfWork.Save();
           

            TempData["Success"] = "OrderDeatils Updated Successfully";

            return RedirectToAction(nameof(Details), new { orderId = orderHeaderFroDb.Id });


        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Adm + "," + SD.Role_Emp)]
        public async Task<IActionResult> StartProcessing()
        {
            await unitOfWork.OrderHeader.UpdateStatus(OrderVM.OrderHeader.Id, SD.StatusInProcess);
            await unitOfWork.Save();
            TempData["Success"] = "Order Details Updated Successfully.";
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Adm + "," + SD.Role_Emp)]
        public async Task<IActionResult> ShipOrder()
        {

            var orderHeader = await unitOfWork.OrderHeader.GetFirstOrDefaultAsync(x=> x.Id == OrderVM.OrderHeader.Id);
            orderHeader.TrackingNumber = OrderVM.OrderHeader.TrackingNumber;
            orderHeader.Carrier = OrderVM.OrderHeader.Carrier;
            orderHeader.OrderStatus = SD.StatusShipped;
            orderHeader.ShippingDate = DateTime.Now;
            if (orderHeader.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                orderHeader.PaymentDueDate = DateTime.Now.AddDays(30);
            }

            await unitOfWork.OrderHeader.CreateOrUpdateAsync(orderHeader);
            await unitOfWork.Save();
            TempData["Success"] = "Order Shipped Successfully.";
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });
        }
        [HttpPost]
        [Authorize(Roles = SD.Role_Adm + "," + SD.Role_Emp)]
        public async Task<IActionResult> CancelOrder()
        {

            var orderHeader = await unitOfWork.OrderHeader.GetFirstOrDefaultAsync(u => u.Id == OrderVM.OrderHeader.Id);

            if (orderHeader.PaymentStatus == SD.PaymentStatusApproved)
            {
                var options = new RefundCreateOptions
                {
                    Reason = RefundReasons.RequestedByCustomer,
                    PaymentIntent = orderHeader.PaymentIntentId
                };

                var service = new RefundService();
                Refund refund = service.Create(options);

                await unitOfWork.OrderHeader.UpdateStatus(orderHeader.Id, SD.StatusCancelled, SD.StatusRefunded);
            }
            else
            {
                await unitOfWork.OrderHeader.UpdateStatus(orderHeader.Id, SD.StatusCancelled, SD.StatusCancelled);
            }
            await unitOfWork.Save();
            TempData["Success"] = "Order Cancelled Successfully.";
            return RedirectToAction(nameof(Details), new { orderId = OrderVM.OrderHeader.Id });

        }

        [HttpPost]
        [ActionName("Details")]
        public async Task<IActionResult> Details_Pay_Now()
        {
            OrderVM.OrderHeader = await unitOfWork.OrderHeader.GetFirstOrDefaultAsync(x => x.Id == OrderVM.OrderHeader.Id, false, x => x.ApplicationUser);
            OrderVM.OrderDetial = await unitOfWork.OrderDetail.GetAsync(x => x.OrderHeaderId == OrderVM.OrderHeader.Id, false, x => x.Product);
               var domain = Request.Scheme + "://" + Request.Host.Value + "/";
            var options = new SessionCreateOptions
            {
                SuccessUrl = domain + $"admin/order/PaymentConfirmation?orderHeaderId={OrderVM.OrderHeader.Id}",
                CancelUrl = domain + $"admin/order/details?orderId={OrderVM.OrderHeader.Id}",
                LineItems = new List<SessionLineItemOptions>(),


                Mode = "payment",


            };
            foreach (var item in OrderVM.OrderDetial)
            {
                var sessionLineItem = new SessionLineItemOptions
                {
                    PriceData = new SessionLineItemPriceDataOptions
                    {
                        UnitAmount = (long)(item.Price * 100), // $20.50 => 2050
                        Currency = "usd",
                        ProductData = new SessionLineItemPriceDataProductDataOptions
                        {
                            Name = item.Product.Title
                        }
                    },
                    Quantity = item.Count
                };
                options.LineItems.Add(sessionLineItem);
            }
            var service = new SessionService();
            Session session = service.Create(options);
            await unitOfWork.OrderHeader.UpdateStripePaymentID(OrderVM.OrderHeader.Id, session.Id, session.PaymentIntentId);
            await unitOfWork.Save();
            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);


        }
        public async Task<ActionResult> PaymentConfirmation(int orderHeaderId)
        {
            OrderHeader orderHeader = await unitOfWork.OrderHeader.GetFirstOrDefaultAsync(x => x.Id == orderHeaderId);
            if (orderHeader.PaymentStatus == SD.PaymentStatusDelayedPayment)
            {
                //this is an order by company

                var service = new SessionService();
                Session session = service.Get(orderHeader.SessionId);

                if (session.PaymentStatus.ToLower() == "paid")
                {
                    await unitOfWork.OrderHeader.UpdateStripePaymentID(orderHeaderId, session.Id, session.PaymentIntentId);
                    await unitOfWork.OrderHeader.UpdateStatus(orderHeaderId, orderHeader.OrderStatus, SD.PaymentStatusApproved);
                    await unitOfWork.Save();
                }

            }

            return View(orderHeaderId);


        }


        [HttpGet]
        public async Task<IActionResult> GetAll(string status)
        {
             await unitOfWork.OrderHeader.GetAsync(null, false, x => x.ApplicationUser);

            IEnumerable<OrderHeader> objOrders;


            if (User.IsInRole(SD.Role_Adm) || User.IsInRole(SD.Role_Emp))
            {
                objOrders = await unitOfWork.OrderHeader.GetAsync(null, false, x => x.ApplicationUser);

            }
            else
            {

                var claimsIdentity = (ClaimsIdentity?)User.Identity;
                var userId = claimsIdentity?.FindFirst(ClaimTypes.NameIdentifier)?.Value;

                objOrders = await unitOfWork.OrderHeader
                    .GetAsync(x => x.ApplicationUserId == userId,false,x=>x.ApplicationUser);
            }
            switch (status)
            {
                case "pending":
                    objOrders = objOrders.Where(x => x.PaymentStatus == SD.PaymentStatusDelayedPayment);
                    break;
                case "inprocess":
                    objOrders = objOrders.Where(x => x.OrderStatus == SD.StatusInProcess);

                    break;
                case "completed":
                    objOrders = objOrders.Where(x => x.OrderStatus == SD.StatusShipped);
                    break;
                case "approved":
                    objOrders = objOrders.Where(x => x.OrderStatus == SD.StatusApproved);
                    break;
                default:
                    break;
            }


            return Json(new { data = objOrders });
        }

        #endregion
    }
}

BulkyWeb/Areas/Admin/Controllers/UserController.cs
using BulkyBook.Data;
using BulkyBook.DataAccess.Extend;
using BulkyBook.DataAccess.Repository;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Models;
using BulkyBook.Models.ViewModels;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace BulkyBookWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.Role_Adm)]
    public class UserController : Controller
    {



        #region prop
        private readonly IUnitOfWork unitOfWork;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<IdentityUser> userManager;

        #endregion


        #region Ctor
        public UserController(IUnitOfWork unitOfWork,RoleManager<IdentityRole> roleManager,UserManager<IdentityUser> userManager)
        {
            this.unitOfWork = unitOfWork;
            this.roleManager = roleManager;
            this.userManager = userManager;
        }
        #endregion


        #region Actions
        public async Task<IActionResult> Index()
        {

           
            return View();
        }


        public async Task<IActionResult> RoleManagement(string userId)
        {
            // Retrieve the user with tracking enabled for updates
            var applicationUser = await unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(
                u => u.Id == userId,
                 false,// Enable tracking
                x => x.Company // Include navigation property
            );

            if (applicationUser == null)
            {
                return NotFound(); // Handle case where user is not found
            }

            // Retrieve the user's current role
            var roles = await userManager.GetRolesAsync(applicationUser);
            var currentRole = roles.FirstOrDefault();

            // Prepare the ViewModel
            var roleVM = new RoleManagementVM
            {
                ApplicationUser = applicationUser,
                RoleList = roleManager.Roles.Select(role => new SelectListItem
                {
                    Text = role.Name,
                    Value = role.Name
                }),
                CompanyList = (await unitOfWork.Company.GetAsync()).Select(company => new SelectListItem
                {
                    Text = company.Name,
                    Value = company.Id.ToString()
                })
            };

            // Assign the current role to the ViewModel
            roleVM.ApplicationUser.Role = currentRole;

            // Return the view with the ViewModel
            return View(roleVM);
        }


        [HttpPost]
        public async Task<IActionResult> RoleManagement(RoleManagementVM roleManagementVM)
        {

            var applicationUser = await unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(x => x.Id == roleManagementVM.ApplicationUser.Id, true);
        
            if (applicationUser == null)
            {
                return NotFound();
            }
                // Retrieve the current role
                var oldRole = (await userManager.GetRolesAsync(applicationUser)).FirstOrDefault();

            if (roleManagementVM.ApplicationUser.Role != oldRole)
            {
                // Role was updated
                if (roleManagementVM.ApplicationUser.Role == SD.Role_Comp)
                {
                    applicationUser.CompanyId = roleManagementVM.ApplicationUser.CompanyId;
                }
                else if (oldRole == SD.Role_Comp)
                {
                    applicationUser.CompanyId = null;
                }

                // Update the user
                await unitOfWork.ApplicationUser.CreateOrUpdateAsync(applicationUser);
                await unitOfWork.Save();

                if (!string.IsNullOrEmpty(oldRole))
                {
                    await userManager.RemoveFromRoleAsync(applicationUser, oldRole);
                }

                await userManager.AddToRoleAsync(applicationUser, roleManagementVM.ApplicationUser.Role);
            }
            else if (oldRole == SD.Role_Comp && applicationUser.CompanyId != roleManagementVM.ApplicationUser.CompanyId)
            {
                // Only update CompanyId if it changed
                applicationUser.CompanyId = roleManagementVM.ApplicationUser.CompanyId;
                await unitOfWork.ApplicationUser.CreateOrUpdateAsync(applicationUser);
                await unitOfWork.Save();
            }

            return RedirectToAction("Index");
        }




        #endregion

        #region API CALLS

        [HttpGet]
        public async Task<IActionResult> GetAll()
        {
            var UserList = await unitOfWork.ApplicationUser.GetAsync(null,false,x=>x.Company);

            


            foreach (var user in UserList)
            {
                user.Role = (await userManager.GetRolesAsync(user)).FirstOrDefault();
                if (user.Company == null)
                {
                    user.Company = new Company()
                    {
                        Name = ""
                    };
                }
            }
            return Json(new { data = UserList });
        }


        [HttpPost]
        public async Task<IActionResult> LockUnlock([FromBody] string id)
        {

            var objFromDb = await unitOfWork.ApplicationUser.GetFirstOrDefaultAsync(u => u.Id == id);
            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while Locking/Unlocking" });
            }

            if (objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.Now)
            {
                //user is currently locked and we need to unlock them
                objFromDb.LockoutEnd = DateTime.Now;
            }
            else
            {
                objFromDb.LockoutEnd = DateTime.Now.AddYears(1000);
            }
            await unitOfWork.ApplicationUser.CreateOrUpdateAsync(objFromDb);
            await unitOfWork.Save();
            return Json(new { success = true, message = "Operation Successful" });
        }

        #endregion
    }
}

BulkyWeb/ViewComponents/ShoppingCartViewComponent.cs
using BulkyBook.DataAccess.Repository;
using BulkyBook.DataAccess.Repository.IRepository;
using BulkyBook.Utility;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BulkyBookWeb.ViewComponents
{
    public class ShoppingCartViewComponent:ViewComponent
    {
        private readonly IUnitOfWork unitOfWork;

        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            this.unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity?)User.Identity;
            var userId = claimsIdentity?.FindFirst(ClaimTypes.NameIdentifier)?.Value;

            if (userId != null)
            {

                if (HttpContext.Session.GetInt32(SD.SessionCart) == null)
                {
                    HttpContext.Session.SetInt32(SD.SessionCart,
                  (await unitOfWork.ShoppingCart.GetAsync(u => u.ApplicationUserId == userId)).Count());
                }
                return View(HttpContext.Session.GetInt32(SD.SessionCart));
            }
            else
            {
                HttpContext.Session.Clear();
                return View(0);

            }

        }

    }
}

BulkyWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BulkyBookWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
   
     <link href="~/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
           <link href="~/toastr.js/toastr.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        <link rel="stylesheet" href="//cdn.datatables.net/1.13.3/css/jquery.dataTables.min.css" />


 

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyBookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link"  asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Orders</a>
                        </li>
                          @if (User.IsInRole(SD.Role_Adm))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Content Management
                                </a>
                             <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Identity"  asp-page="/Account/Register">Create User</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="nav-link text-dark" asp-area="Admin" asp-controller="User" asp-action="Index">Manage Users</a>
                                    </li>
                                </ul>

                            </li>
                        }
                      
                        
                           <li class="nav-item">
                                <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                   @await Component.InvokeAsync("ShoppingCart")
                                </a>
                            </li>
                        
                    </ul>
                        
                        
                        <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">

            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-primary text-muted">
        <div class="container">
            <center>

                Made With <i class="bi bi-heart-fill"></i> Gamal Elbatawy
            </center>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
   <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

     <script src="//cdn.datatables.net/1.13.3/js/jquery.dataTables.min.js" asp-append-version="true"></script>

    <script src="https://cdn.tiny.cloud/1/qd1iwwglhna1d8428d3vcgmsxl20spm7st9vbz77o1rb9q9w/tinymce/7/tinymce.min.js" referrerpolicy="origin"></script>

    <script src="~/toastr.js/toastr.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BulkyWeb/Views/Shared/_Notification.cshtml
@if(TempData["Success"]!=null){

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/toastr.js/toastr.min.js"></script>
        <script type="text/javascript">


            toastr.success('@TempData["success"]')

            </script>
}

@if (TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/toastr.js/toastr.min.js"></script>
    <script type="text/javascript">

        toastr.error('@TempData["success"]')

    </script>
}